# I don't claim for this Makefile to be 'correct'
# but it let me test some basic win32 stuff on debian
# using the mingw32 package

LIB_PREFIX=
LIB_SUFFIX=.o
STATIC_LIB=1
CC=i586-mingw32msvc-gcc
export STATIC_LIB
export CC

include Makefile
